version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    target-branch: "stg"
    open-pull-requests-limit: 5
    assignees:
      - "ippei-shimizu"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    target-branch: "stg"
    open-pull-requests-limit: 5
    assignees:
      - "ippei-shimizu"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "Update"
      include: "scope"
