import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@app/components/header/Header";
import { Providers } from "@app/providers";
import NavigationMenu from "@app/components/header/NavigationMenu";
import { AuthProvider } from "@app/contexts/useAuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Buzz Base",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="h-full">
      <body className={`${inter.className} bg-main text-white h-full`}>
        <AuthProvider>
          <Providers>
            <div>
              <Header />
              <main>{children}</main>
              <NavigationMenu />
            </div>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
